{
 "title": "KubeDB / Kafka / Connect",
 "description": "Kafka dashboard for metrics exported by Prometheus Operator",
 "tags": [
  "kafka",
  "kubedb",
  "KRaft",
  "JMX exporter"
 ],
 "time": { "from": "2023-12-13T12:00:03.413Z", "to": "2023-12-13T12:02:42.567Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "container",
    "query": {
     "query": "label_values(jvm_info{container=\"kafka-connect\"},container)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(jvm_info{container=\"$container\"},service)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(jvm_info{container=\"$container\", service=\"$service\"},pod)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(jvm_info{pod=\"$pod\", service=\"$service\"},namespace)"
    }
   },
   {
    "name": "memarea",
    "label": "mem area",
    "query": {
     "query": "label_values(jvm_memory_bytes_used{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\", container=\"$container\"},area)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Kafka Connect Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",container=\"$container\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",container=\"$container\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",container=\"$container\"}"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(jvm_info{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",container=\"$container\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  {
   "title": "Average number of CPUs used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{container=\"$container\", namespace=\"$namespace\", pod=\"$pod\",container=\"$container\"}[5m])\n) by (namespace,pod)"
    }
   ]
  },
  {
   "title": "Memory area [$memarea]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "repeat": "memarea",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"$memarea\",namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",container=\"$container\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"$memarea\",namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",container=\"$container\"}",
     "legendFormat": "Upper limit"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"$memarea\",namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",container=\"$container\"} / jvm_memory_bytes_max >= 0",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "GC time increase",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",container=\"$container\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC count increase",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",container=\"$container\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "jvm classes loaded",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_currently_loaded{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",container=\"$container\"}",
     "legendFormat": "$pod"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",container=\"$container\"}",
     "legendFormat": "JVM current threads"
    },
    {
     "expr": "jvm_threads_daemon{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\",container=\"$container\"}",
     "legendFormat": "JVM daemon threads"
    },
    {
     "expr": "jvm_threads_deadlocked{namespace=\"$namespace\",service=\"$service\",pod=\"$pod\"}",
     "legendFormat": "JVM deadlocked threads"
    }
   ]
  },
  {
   "title": "Broker Topic Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Messages in topics",
   "type": "table",
   "description": "Incoming message rate per topic. Omitting 'topic=(...)' will yield the all-topic rate.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total{namespace=\"$namespace\", pod=\"$pod\", service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Byte in rate from clients",
   "type": "table",
   "description": "Byte in (from the clients) rate per topic. Omitting 'topic=(...)' will yield the all-topic rate.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesin_total{namespace=\"$namespace\", pod=\"$pod\", service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Fetch request rate",
   "type": "table",
   "description": "Fetch request (from clients or followers) rate per topic.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_totalfetchrequests_total{namespace=\"$namespace\", pod=\"$pod\", service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Byte out rate to other brokers",
   "type": "table",
   "description": "Byte out (to the other brokers) rate per topic.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_replicationbytesout_total{namespace=\"$namespace\", pod=\"$pod\", service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Byte in rate from other brokers",
   "type": "table",
   "description": "Byte in (from the other brokers) rate per topic. Omitting 'topic=(...)' will yield the all-topic rate.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_replicationbytesin_total{namespace=\"$namespace\", pod=\"$pod\", service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Produce request rate\t",
   "type": "table",
   "description": "Produce request rate per topic.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_totalproducerequests_total{namespace=\"$namespace\", pod=\"$pod\", service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Failed produce request rate\t",
   "type": "table",
   "description": "Failed Peoducer request (from clients or followers) rate per topic.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_failedproducerequests_total{namespace=\"$namespace\", pod=\"$pod\", service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Byte out rate to clients",
   "type": "table",
   "description": "Byte out (to the clients) rate per topic.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesout_total{namespace=\"$namespace\", pod=\"$pod\", service=\"$service\"}"
    }
   ]
  },
  {
   "title": "First offset partitions",
   "type": "table",
   "description": "The first offset in a partition.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "kafka_log_log_logstartoffset{namespace=\"$namespace\", pod=\"$pod\", service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Last offset partitions",
   "type": "table",
   "description": "The last offset in a partition.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "kafka_log_log_logendoffset{namespace=\"$namespace\", pod=\"$pod\", service=\"$service\"}"
    }
   ]
  },
  {
   "title": "The average fraction of time the request handler threads are idle",
   "type": "timeseries",
   "description": "between 0 and 1, ideally > 0.3",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "kafka_server_kafkarequesthandlerpool_requesthandleravgidle_percent{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Failed fetch request rate\t",
   "type": "table",
   "description": "Failed Fetch request (from clients or followers) rate per topic.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_failedfetchrequests_total{namespace=\"$namespace\", pod=\"$pod\", service=\"$service\"}"
    }
   ]
  },
  {
   "title": "KRaft Quorum Monitoring Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Leader ID",
   "type": "stat",
   "description": "The current quorum leader's id; -1 indicates unknown.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_raft_metrics_current_leader{namespace=\"$namespace\", pod=\"$pod\", service=\"$service\"}"
    }
   ]
  },
  {
   "title": "High Watermark\t",
   "type": "stat",
   "description": "The high watermark maintained on this member; -1 if it is unknown.\t",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_raft_metrics_high_watermark{container=\"$container\", namespace=\"$namespace\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Number of Unknown Voter Connections",
   "type": "stat",
   "description": "Number of unknown voters whose connection information is not cached. This value of this metric is always 0.\t",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_raft_metrics_number_unknown_voter_connections{container=\"$container\", namespace=\"$namespace\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Current quorum epoch",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_raft_metrics_current_epoch{container=\"$container\", namespace=\"$namespace\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Average Commit Latency\t",
   "type": "stat",
   "description": "The average time in milliseconds to commit an entry in the raft log",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_raft_metrics_commit_latency_avg{container=\"$container\", namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Append Records Rate\t",
   "type": "table",
   "description": "The average number of records appended per sec by the leader of the raft quorum.\t",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "kafka_server_raft_metrics_append_records_rate{container=\"$container\", namespace=\"$namespace\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Current Voted\t",
   "type": "table",
   "description": "The current voted leader's id; -1 indicates not voted for anyone.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "kafka_server_raft_metrics_current_vote{namespace=\"$namespace\", service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Raft Log End Offset\t",
   "type": "stat",
   "description": "The current raft log end offset.\t",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 95 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_raft_metrics_log_end_offset{container=\"$container\", namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Average Poll Idle Ratio\t",
   "type": "gauge",
   "description": "The average fraction of time the client's poll() is idle as opposed to waiting for the user code to process records.\t",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 95 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_raft_metrics_poll_idle_ratio_avg{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "KRaft Controller Monitoring Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of Active Brokers",
   "type": "stat",
   "description": "The number of active brokers as observed by this Controller.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activebrokercount{namespace=\"$namespace\", pod=\"$pod\", service=\"$service\"}\n"
    }
   ]
  },
  {
   "title": "Number of active controllers",
   "type": "stat",
   "description": "The number of Active Controllers on this node.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{namespace=\"$namespace\", pod=\"$pod\", service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Fenced Broker Count\t",
   "type": "stat",
   "description": "The number of fenced brokers as observed by this Controller",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_fencedbrokercount{container=\"$container\", namespace=\"$namespace\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Metadata Error Count",
   "type": "stat",
   "description": "The number of times this controller node has encountered an error during metadata log processing.\t",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 101 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_metadataerrorcount{container=\"$container\", namespace=\"$namespace\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Global Partition Count\t",
   "type": "table",
   "description": "The number of global partitions as observed by this Controller.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_globalpartitioncount"
    }
   ]
  },
  {
   "title": "Global Topic count",
   "type": "table",
   "description": "The number of global topics as observed by this Controller.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_globaltopiccount",
     "legendFormat": "{{ $pod }}"
    }
   ]
  },
  {
   "title": "Offline Partition Count\t",
   "type": "table",
   "description": "The number of offline topic partitions (non-internal) as observed by this Controller.\t",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_offlinepartitionscount"
    }
   ]
  },
  {
   "title": "Preferred Replica Imbalance Count\t",
   "type": "table",
   "description": "The count of topic partitions for which the leader is not the preferred leader.\t",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_preferredreplicaimbalancecount"
    }
   ]
  }
 ]
}