{
 "title": "KubeDB / Kafka / Connect",
 "description": "Kafka Connect dashboard for metrics exported by Prometheus Operator",
 "tags": [
  "kafka",
  "kubedb",
  "JMX exporter",
  "kafka-connect"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(jvm_info{container=\"$container\"},namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(jvm_info{namespace=\"$namespace\"},service)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(jvm_info{container=\"kafka-connect\"},container)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(jvm_info{service=\"$service\"},pod)"
    }
   },
   {
    "name": "memarea",
    "label": "mem area",
    "query": {
     "query": "label_values(jvm_memory_bytes_used{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\", container=\"$container\"},area)"
    }
   },
   {
    "name": "connector",
    "query": {
     "query": "label_values(kafka_connect_connector_task_pause_ratio{container=\"$container\", namespace=\"$namespace\", service=\"$service\"},connector)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connectors not running",
     "type": "gauge",
     "description": "Subtracts running connectors from all connectors; Alerts when any are found.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (kafka_connect_connector_status) - sum(kafka_connect_connector_status{status=\"running\"})",
       "legendFormat": "connectors not running"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Connect Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(jvm_info{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  {
   "title": "Average number of CPUs used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{container=\"$container\", namespace=\"$namespace\", pod=~\"$pod\",container=\"$container\"}[5m])\n) by (namespace,pod)"
    }
   ]
  },
  {
   "title": "Connector repartition per status",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum (kafka_connect_connector_status{connector=~\"$connector\",status=\"running\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum (kafka_connect_connector_status{connector=~\"$connector\",status=\"stopped\"})",
     "legendFormat": "stopped"
    },
    {
     "expr": "sum (kafka_connect_connector_status{connector=~\"$connector\",status=\"paused\"})",
     "legendFormat": "paused"
    }
   ]
  },
  {
   "title": "Task repartition per status",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_running_task_count{pod=~\"$pod\",connector=~\"$connector\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count{pod=~\"$pod\",connector=~\"$connector\"})",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count{pod=~\"$pod\",connector=~\"$connector\"})",
     "legendFormat": "paused"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{pod=~\"$pod\",connector=~\"$connector\"})",
     "legendFormat": "unassigned"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{pod=~\"$pod\",connector=~\"$connector\"})",
     "legendFormat": "destroyed"
    }
   ]
  },
  {
   "title": "GC time increase",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC count increase",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "jvm classes loaded",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_classes_currently_loaded{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}",
     "legendFormat": "$pod"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_current{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}",
     "legendFormat": "JVM current threads"
    },
    {
     "expr": "jvm_threads_daemon{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}",
     "legendFormat": "JVM daemon threads"
    },
    {
     "expr": "jvm_threads_deadlocked{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}",
     "legendFormat": "JVM deadlocked threads"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{namespace=\"$namespace\",pod=~\"$pod\",container=\"$container\",service=\"$service\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory area [$memarea]",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "repeat": "memarea",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=~\"$memarea\",pod=~\"$pod\"}/(1024*1024)",
     "legendFormat": "Used MB/s"
    },
    {
     "expr": " jvm_memory_bytes_max{area=~\"$memarea\",pod=~\"$pod\"}/(1024*1024)",
     "legendFormat": "Upper limit MB/s"
    },
    {
     "expr": "jvm_memory_bytes_used{area=~\"$memarea\",pod=~\"$pod\"} * 100 / jvm_memory_bytes_max >= 0",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "Connect Worker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connect Worker",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_connect_app_info{pod=~\"$pod\",start_time_ms!=\"\"}"
      },
      {
       "expr": "kafka_connect_app_info{pod=~\"$pod\",version!=\"\"}"
      },
      {
       "expr": "sum by (pod) (kafka_connect_worker_connector_count{pod=~\"$pod\"})"
      },
      {
       "expr": "sum by (pod) (kafka_connect_worker_connector_startup_success_total{pod=~\"$pod\"})"
      },
      {
       "expr": "sum by (pod) (kafka_connect_worker_connector_startup_failure_total{pod=~\"$pod\"})"
      },
      {
       "expr": "sum by (pod) (kafka_connect_worker_task_count{pod=~\"$pod\"})"
      },
      {
       "expr": "sum by (pod) (kafka_connect_worker_task_startup_success_total{pod=~\"$pod\"})"
      },
      {
       "expr": "sum by (pod) (kafka_connect_worker_task_startup_failure_total{pod=~\"$pod\"})"
      }
     ]
    },
    {
     "title": "Network IO Rate",
     "type": "timeseries",
     "description": "Average number of network operations (reads or writes) on all connections per second",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "kafka_connect_network_io_rate{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Incoming Byte Rate",
     "type": "timeseries",
     "description": "Bytes per second read off all sockets",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "kafka_connect_incoming_byte_rate{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Outgoing Byte Rate",
     "type": "timeseries",
     "description": "Average number of outgoing bytes sent per second to all servers",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "kafka_connect_outgoing_byte_rate{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Current number of active connections",
     "type": "timeseries",
     "description": "Current number of active connections",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "connections" } },
     "targets": [
      {
       "expr": "kafka_connect_connection_count{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Failed authentication connections",
     "type": "timeseries",
     "description": "Connections that failed authentication",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "connections" } },
     "targets": [
      {
       "expr": "kafka_connect_failed_authentication_total{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Success authentication connections",
     "type": "timeseries",
     "description": "Connections that were successfully authenticated using SASL or SSL",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "connections" } },
     "targets": [
      {
       "expr": "kafka_connect_successful_authentication_rate{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Average number of requests",
     "type": "timeseries",
     "description": "Average number of requests sent per second",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "kafka_connect_request_rate{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Responses received and sent",
     "type": "timeseries",
     "description": "Responses received and sent per second",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "kafka_connect_response_rate{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "IO Ratio",
     "type": "timeseries",
     "description": "Fraction of time the I/O thread spent doing I/O",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "kafka_connect_io_ratio{pod=~\"$pod\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  { "title": "Connector Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Connectors",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_replace(kafka_connect_connector_info{pod=~\"$pod\",connector=~\"$connector\",status!=\"\"}, \"status\", \"1\", \"status\", \"running\"), \"status\", \"2\", \"status\", \"paused\"), \"status\", \"3\", \"status\", \"stopped\")"
    },
    {
     "expr": "kafka_connect_connector_info{pod=~\"$pod\",connector=~\"$connector\",connector_type!=\"\"}"
    },
    {
     "expr": "kafka_connect_connector_info{pod=~\"$pod\",connector=~\"$connector\",connector_version!=\"\"}"
    },
    {
     "expr": "kafka_connect_connector_info{pod=~\"$pod\",connector=~\"$connector\",connector_class!=\"\"}"
    },
    {
     "expr": "sum by (connector) (kafka_connect_worker_connector_total_task_count{pod=~\"$pod\",connector=~\"$connector\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_worker_connector_running_task_count{pod=~\"$pod\",connector=~\"$connector\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_worker_connector_failed_task_count{pod=~\"$pod\",connector=~\"$connector\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_worker_connector_paused_task_count{pod=~\"$pod\",connector=~\"$connector\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_worker_connector_destroyed_task_count{pod=~\"$pod\",connector=~\"$connector\"})"
    },
    {
     "expr": "sum by (connector) (kafka_connect_worker_connector_unassigned_task_count{pod=~\"$pod\",connector=~\"$connector\"})"
    }
   ]
  },
  { "title": "Rebalance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Rebalances average time",
   "type": "timeseries",
   "description": "Rebalances average time",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_worker_rebalance_rebalance_avg_time_ms{pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "($pod) Time since last rebalance ",
   "type": "stat",
   "description": "Time since last rebalance",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 72 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "clockms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_worker_rebalance_time_since_last_rebalance_ms{pod=~\"$pod\"} >= 0"
    }
   ]
  },
  { "title": "Task Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Task Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_total_task_count{connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_running_task_count{connector=~\"$connector\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks Paused",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count{connector=~\"$connector\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks Tasks Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count{connector=~\"$connector\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks Unassigned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{connector=~\"$connector\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks Destroyed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{connector=~\"$connector\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch Size Average",
   "type": "timeseries",
   "description": "Average size of the batches processed by the connector",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_batch_size_avg{connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Offset commit success percentage",
   "type": "timeseries",
   "description": "Average percentage of the task’s offset commit attempts that succeeded",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_offset_commit_success_percentage{connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Batch Size Max",
   "type": "timeseries",
   "description": "Maximum size of the batches processed by the connector",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_batch_size_max{connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Running ratio",
   "type": "timeseries",
   "description": "The fraction of time this task has spent in the running state.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_running_ratio{connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Offset commit Average Time",
   "type": "timeseries",
   "description": "The average time in milliseconds taken by this task to commit offsets",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_offset_commit_avg_time_ms{connector=~\"$connector\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Task Error Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total record failures",
     "type": "graph",
     "description": "Total number of failures seen by task",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 116 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_task_error_total_record_failures{pod=~\"$pod\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Total errors logged",
     "type": "graph",
     "description": "The number of messages that was logged into either the dead letter queue or with Log4j",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 116 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_task_error_total_errors_logged{pod=~\"$pod\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Dead letter queue Produce requests",
     "type": "graph",
     "description": "Number of produce requests to the dead letter queue",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 116 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_task_error_deadletterqueue_produce_requests{pod=~\"$pod\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Total record errors",
     "type": "graph",
     "description": "Total number of errors seen by task",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 123 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_task_error_total_record_errors{pod=~\"$pod\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Total retries",
     "type": "graph",
     "description": "Total number of retries made by task",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 123 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_task_error_total_retries{pod=~\"$pod\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Total record skipped",
     "type": "graph",
     "description": "Total number of records skipped by task",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 123 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_task_error_total_records_skipped{pod=~\"$pod\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Dead letter queue Produce requests",
     "type": "graph",
     "description": "Number of produce requests to the dead letter queue",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 130 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_task_error_deadletterqueue_produce_requests{pod=~\"$pod\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    }
   ]
  },
  { "title": "Source Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 } },
  {
   "title": "Poll Batch Average time",
   "type": "graph",
   "description": "The average time in milliseconds taken by this task to poll for a batch of source records",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_source_task_poll_batch_avg_time_ms{pod=~\"$pod\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Poll Batch Max time",
   "type": "graph",
   "description": "The maximum time in milliseconds taken by this task to poll for a batch of source records",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 124 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_source_task_poll_batch_max_time_ms{pod=~\"$pod\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Source Record Poll rate",
   "type": "graph",
   "description": "The average per-second number of records produced/polled (before transformation) by this task belonging to the named source connector in this worker.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 124 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_source_task_source_record_poll_rate{pod=~\"$pod\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Source Record Write rate",
   "type": "graph",
   "description": "The average per-second number of records output from the transformations and written to Kafka for this task belonging to the named source connector in this worker. This is after transformations are applied and excludes any records filtered out by the transformations.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_source_task_source_record_write_rate{pod=~\"$pod\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Source Record Active Count average",
   "type": "graph",
   "description": "The average number of records that have been produced by this task but not yet completely written to Kafka.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_connect_source_task_source_record_active_count{pod=~\"$pod\",connector=~\"$connector\",task!=\"\"})",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Source Record Active Count max",
   "type": "graph",
   "description": "The maximum number of records that have been produced by this task but not yet completely written to Kafka.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 131 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kafka_connect_source_task_source_record_active_count{pod=~\"$pod\",connector=~\"$connector\",task!=\"\"})",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  { "title": "Sink Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 138 } },
  {
   "title": "Partition Count",
   "type": "timeseries",
   "description": "The number of topic partitions assigned to this task belonging to the named sink connector in this worker.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_sink_task_partition_count{pod=~\"$pod\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Put Batch Average time",
   "type": "timeseries",
   "description": "The average time in milliseconds taken by this task to put a batch of sinks records",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_sink_task_put_batch_avg_time_ms{pod=~\"$pod\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Put Batch Max time",
   "type": "timeseries",
   "description": "The maximum time in milliseconds taken by this task to put a batch of sinks records",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_sink_task_put_batch_max_time_ms{pod=~\"$pod\",connector=~\"$connector\",task!=\"\"}",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  }
 ]
}