{
 "title": "KubeDB / Kafka / Connects",
 "description": "Monitor Apache Kafka Connect",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(kafka_connect_commit_id_info,instance)"
    }
   },
   {
    "name": "connector",
    "query": {
     "query": "label_values(kafka_connect_connector_task_pause_ratio,connector)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Connectors not running",
     "type": "gauge",
     "description": "Subtracts running connectors from all connectors; Alerts when any are found.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (kafka_connect_connector_status) - sum(kafka_connect_connector_status{status=\"running\"})",
       "legendFormat": "connectors not running"
      }
     ]
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tasks Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_total_task_count{instance=~\"$instance\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_running_task_count{instance=~\"$instance\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Paused",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count{instance=~\"$instance\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count{instance=~\"$instance\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Unassigned",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{instance=~\"$instance\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Tasks Destroyed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{instance=~\"$instance\",connector=~\"$connector\"})"
    }
   ]
  },
  {
   "title": "Connector repartition per status",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum (kafka_connect_connector_status{connector=~\"$connector\",status=\"running\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum (kafka_connect_connector_status{connector=~\"$connector\",status=\"stopped\"})",
     "legendFormat": "stopped"
    },
    {
     "expr": "sum (kafka_connect_connector_status{connector=~\"$connector\",status=\"paused\"})",
     "legendFormat": "paused"
    }
   ]
  },
  {
   "title": "Task repartition per status",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_running_task_count{instance=~\"$instance\",connector=~\"$connector\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count{instance=~\"$instance\",connector=~\"$connector\"})",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count{instance=~\"$instance\",connector=~\"$connector\"})",
     "legendFormat": "paused"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{instance=~\"$instance\",connector=~\"$connector\"})",
     "legendFormat": "unassigned"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{instance=~\"$instance\",connector=~\"$connector\"})",
     "legendFormat": "destroyed"
    }
   ]
  },
  {
   "title": "Status of connectors",
   "type": "graph",
   "description": "Status of connectors over time",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_connect_connector_status{connector=~\"$connector\",status!=\"\"}) by (status) ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Status of tasks",
   "type": "graph",
   "description": "Status of tasks over time",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_connect_worker_connector_running_task_count{instance=~\"$instance\",connector=~\"$connector\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_failed_task_count{instance=~\"$instance\",connector=~\"$connector\"})",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_paused_task_count{instance=~\"$instance\",connector=~\"$connector\"})",
     "legendFormat": "paused"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_destroyed_task_count{instance=~\"$instance\",connector=~\"$connector\"})",
     "legendFormat": "destroyed"
    },
    {
     "expr": "sum(kafka_connect_worker_connector_unassigned_task_count{instance=~\"$instance\",connector=~\"$connector\"})",
     "legendFormat": "unassigned"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percent", "label": "Cores" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"connect\",instance=~\"$instance\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum without(area)(jvm_memory_bytes_used{job=\"connect\",instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "jvm_memory_bytes_max{job=\"connect\",instance=~\"$instance\",area=\"heap\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Memory Used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "percentunit", "label": "% time in GC" }
     ],
     "targets": [
      {
       "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"connect\",instance=~\"$instance\"}[5m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connect Worker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Connect Worker",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_connect_app_info{instance=~\"$instance\",start_time_ms!=\"\"}"
      },
      {
       "expr": "kafka_connect_app_info{instance=~\"$instance\",version!=\"\"}"
      },
      {
       "expr": "sum by (instance) (kafka_connect_worker_connector_count{instance=~\"$instance\"})"
      },
      {
       "expr": "sum by (instance) (kafka_connect_worker_connector_startup_success_total{instance=~\"$instance\"})"
      },
      {
       "expr": "sum by (instance) (kafka_connect_worker_connector_startup_failure_total{instance=~\"$instance\"})"
      },
      {
       "expr": "sum by (instance) (kafka_connect_worker_task_count{instance=~\"$instance\"})"
      },
      {
       "expr": "sum by (instance) (kafka_connect_worker_task_startup_success_total{instance=~\"$instance\"})"
      },
      {
       "expr": "sum by (instance) (kafka_connect_worker_task_startup_failure_total{instance=~\"$instance\"})"
      }
     ]
    },
    {
     "title": "Network IO Rate",
     "type": "timeseries",
     "description": "Average number of network operations (reads or writes) on all connections per second",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "kafka_connect_network_io_rate{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Incoming Byte Rate",
     "type": "timeseries",
     "description": "Bytes per second read off all sockets",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "kafka_connect_incoming_byte_rate{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Outgoing Byte Rate",
     "type": "timeseries",
     "description": "Average number of outgoing bytes sent per second to all servers",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "kafka_connect_outgoing_byte_rate{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Current number of active connections",
     "type": "timeseries",
     "description": "Current number of active connections",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "connections" } },
     "targets": [
      {
       "expr": "kafka_connect_connection_count{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Failed authentication connections",
     "type": "timeseries",
     "description": "Connections that failed authentication",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "connections" } },
     "targets": [
      {
       "expr": "kafka_connect_failed_authentication_total{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Success authentication connections",
     "type": "timeseries",
     "description": "Connections that were successfully authenticated using SASL or SSL",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "connections" } },
     "targets": [
      {
       "expr": "kafka_connect_successful_authentication_rate{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Average number of requests",
     "type": "graph",
     "description": "Average number of requests sent per second",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_request_rate{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "Responses received and sent",
     "type": "timeseries",
     "description": "Responses received and sent per second",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "kafka_connect_response_rate{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}-{{client_id}}"
      }
     ]
    },
    {
     "title": "IO Ratio",
     "type": "timeseries",
     "description": "Fraction of time the I/O thread spent doing I/O",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "kafka_connect_io_ratio{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}-{{client_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connector details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Connectors",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace(label_replace(label_replace(kafka_connect_connector_info{instance=~\"$instance\",connector=~\"$connector\",status!=\"\"}, \"status\", \"1\", \"status\", \"running\"), \"status\", \"2\", \"status\", \"paused\"), \"status\", \"3\", \"status\", \"stopped\")"
      },
      {
       "expr": "kafka_connect_connector_info{instance=~\"$instance\",connector=~\"$connector\",connector_type!=\"\"}"
      },
      {
       "expr": "kafka_connect_connector_info{instance=~\"$instance\",connector=~\"$connector\",connector_version!=\"\"}"
      },
      {
       "expr": "kafka_connect_connector_info{instance=~\"$instance\",connector=~\"$connector\",connector_class!=\"\"}"
      },
      {
       "expr": "sum by (connector) (kafka_connect_worker_connector_total_task_count{instance=~\"$instance\",connector=~\"$connector\"})"
      },
      {
       "expr": "sum by (connector) (kafka_connect_worker_connector_running_task_count{instance=~\"$instance\",connector=~\"$connector\"})"
      },
      {
       "expr": "sum by (connector) (kafka_connect_worker_connector_failed_task_count{instance=~\"$instance\",connector=~\"$connector\"})"
      },
      {
       "expr": "sum by (connector) (kafka_connect_worker_connector_paused_task_count{instance=~\"$instance\",connector=~\"$connector\"})"
      },
      {
       "expr": "sum by (connector) (kafka_connect_worker_connector_destroyed_task_count{instance=~\"$instance\",connector=~\"$connector\"})"
      },
      {
       "expr": "sum by (connector) (kafka_connect_worker_connector_unassigned_task_count{instance=~\"$instance\",connector=~\"$connector\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Rebalances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Rebalances average time",
     "type": "graph",
     "description": "Rebalances average time",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_worker_rebalance_rebalance_avg_time_ms{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "($instance) Time since last rebalance ",
     "type": "stat",
     "description": "Time since last rebalance",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
     "repeat": "instance",
     "fieldConfig": { "defaults": { "unit": "clockms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_connect_worker_rebalance_time_since_last_rebalance_ms{instance=~\"$instance\"} >= 0"
      }
     ]
    }
   ]
  },
  {
   "title": "Task metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Batch Size Average",
     "type": "graph",
     "description": "Average size of the batches processed by the connector",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connector_task_batch_size_avg{instance=~\"$instance\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Batch Size Max",
     "type": "graph",
     "description": "Maximum size of the batches processed by the connector",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connector_task_batch_size_max{instance=~\"$instance\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Offset commit success percentage",
     "type": "graph",
     "description": "Average percentage of the task’s offset commit attempts that succeeded",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connector_task_offset_commit_success_percentage{instance=~\"$instance\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Offset commit Average Time",
     "type": "graph",
     "description": "The average time in milliseconds taken by this task to commit offsets",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connector_task_offset_commit_avg_time_ms{instance=~\"$instance\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Running ratio",
     "type": "graph",
     "description": "The fraction of time this task has spent in the running state.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_connector_task_running_ratio{instance=~\"$instance\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Errors metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total record failures",
     "type": "graph",
     "description": "Total number of failures seen by task",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_task_error_total_record_failures{instance=~\"$instance\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Total record errors",
     "type": "graph",
     "description": "Total number of errors seen by task",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_task_error_total_record_errors{instance=~\"$instance\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Total record skipped",
     "type": "graph",
     "description": "Total number of records skipped by task",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 61 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_task_error_total_records_skipped{instance=~\"$instance\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Total errors logged",
     "type": "graph",
     "description": "The number of messages that was logged into either the dead letter queue or with Log4j",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_task_error_total_errors_logged{instance=~\"$instance\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Total retries",
     "type": "graph",
     "description": "Total number of retries made by task",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 68 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_task_error_total_retries{instance=~\"$instance\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Dead letter queue Produce requests",
     "type": "graph",
     "description": "Number of produce requests to the dead letter queue",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 68 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_task_error_deadletterqueue_produce_requests{instance=~\"$instance\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Dead letter queue Produce requests",
     "type": "graph",
     "description": "Number of produce requests to the dead letter queue",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_task_error_deadletterqueue_produce_requests{instance=~\"$instance\",connector=~\"$connector\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Source metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Poll Batch Average time",
     "type": "graph",
     "description": "The average time in milliseconds taken by this task to poll for a batch of source records",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_source_task_poll_batch_avg_time_ms{instance=~\"$instance\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Poll Batch Max time",
     "type": "graph",
     "description": "The maximum time in milliseconds taken by this task to poll for a batch of source records",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_source_task_poll_batch_max_time_ms{instance=~\"$instance\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Source Record Poll rate",
     "type": "graph",
     "description": "The average per-second number of records produced/polled (before transformation) by this task belonging to the named source connector in this worker.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_source_task_source_record_poll_rate{instance=~\"$instance\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Source Record Write rate",
     "type": "graph",
     "description": "The average per-second number of records output from the transformations and written to Kafka for this task belonging to the named source connector in this worker. This is after transformations are applied and excludes any records filtered out by the transformations.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_source_task_source_record_write_rate{instance=~\"$instance\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Source Record Active Count average",
     "type": "graph",
     "description": "The average number of records that have been produced by this task but not yet completely written to Kafka.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(kafka_connect_source_task_source_record_active_count{instance=~\"$instance\",connector=~\"$connector\",task!=\"\"})",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Source Record Active Count max",
     "type": "graph",
     "description": "The maximum number of records that have been produced by this task but not yet completely written to Kafka.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(kafka_connect_source_task_source_record_active_count{instance=~\"$instance\",connector=~\"$connector\",task!=\"\"})",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sink metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Partition Count",
     "type": "graph",
     "description": "The number of topic partitions assigned to this task belonging to the named sink connector in this worker.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_sink_task_partition_count{instance=~\"$instance\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Put Batch Average time",
     "type": "graph",
     "description": "The average time in milliseconds taken by this task to put a batch of sinks records",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_sink_task_put_batch_avg_time_ms{instance=~\"$instance\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    },
    {
     "title": "Put Batch Max time",
     "type": "graph",
     "description": "The maximum time in milliseconds taken by this task to put a batch of sinks records",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_sink_task_put_batch_max_time_ms{instance=~\"$instance\",connector=~\"$connector\",task!=\"\"}",
       "legendFormat": "{{connector}}-{{task}}"
      }
     ]
    }
   ]
  }
 ]
}