apiVersion: v1
kind: Service
metadata:
  name: deploy-dis
  namespace: demo
  labels:
    app: connect-dis
spec:
  selector:
    app: connect-dis
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      name: connect-dis