apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: hey
spec:
  kafka:
    replicas: 3
    version: 3.5.1
    listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
      authentication:
        type: scram-sha-512
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
    jmxOptions: {}
    config:
      log.message.format.version: "3.3"
      inter.broker.protocol.version: "3.3"
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 2
      log.roll.hours: 24
      max.request.size: 536870912
      message.max.bytes: 500000000
      num.partitions: 6
      default.replication.factor: 1
      min.insync.replicas: 1
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafkaExporter: {}